[General]
loglevel = notify
bypass-system = true

[Rule]
DOMAIN-SUFFIX,garena.com,Proxy
DOMAIN-SUFFIX,freefiremobile.com,Proxy
FINAL,DIRECT

[Script]
# Dòng này không được ngắt dòng, phải liền mạch 1 dòng
azexl_aim_drag = type=http-response,pattern=^https?:\/\/(.*\.garena\.com|.*\.freefiremobile\.com)\/.*,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/yseavlong2010-dotcom/NOXERA/refs/heads/main/AimX.js

[MITM]
enable = true
hostname = *.garena.com, *.freefiremobile.com
